name: Checkout freelancer
description: ""
inputs:
  freelancer-folder:
    description: Path to root of freelancer directory
    default: ${{ github.workspace }}
  freelancer-mod:
    description: insert vanilla or discovery
    required: true
  ssh-key-base64:
    description: Key to download freelancer repo
    required: true

runs:
  using: "composite"
  steps:
    - name: Write id_rsa down
      if: ${{ inputs.freelancer-mod == 'vanilla' }}
      shell: python
      run: |
        import base64
        import os
        file_output_name = "${{ github.workspace }}/id_rsa.files.freelancer.vanilla.out"
        with open(file_output_name, "wb", 0o600) as file:
          file.write(base64.b64decode(bytes(os.environ["ID_RSA_FILES_FREELANCER_VANILLA"], encoding='utf8')))
        os.chmod(file_output_name, 0o600)
      env:
        ID_RSA_FILES_FREELANCER_VANILLA: ${{ inputs.ssh-key-base64 }}
    - shell: sh
      run: cat ${{ github.workspace }}/id_rsa.files.freelancer.vanilla.out
    - uses: actions/checkout@v4
      if: ${{ inputs.freelancer-mod == 'vanilla' }}
      with:
        repository: 'darklab8/fl-files-vanilla'
        path: '${{ inputs.freelancer-folder }}'
        ssh-key: ${{ github.workspace }}/id_rsa.files.freelancer.vanilla.out
