# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        freelancer-repository:
          - "fl-data-discovery"
          - "fl-data-vanilla"
    name: Test ${{ matrix.freelancer-repository }}
    steps:
    - uses: actions/checkout@v3

    - uses: actions/checkout@v4
      with:
        repository: 'darklab8/${{ matrix.freelancer-repository }}'
        path: '${{ github.workspace }}/${{ matrix.freelancer-repository }}'
        token: ${{ secrets.FL_DATA_KEY }}
    - run: ls ./fl-data

    - name: Install Task
      run: |
        sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Test
      run: task test -- -v
      env:
        CONFIGS_LOG_LEVEL: "DEBUG"
        CONFIGS_FREELANCER_FOLDER: ${{ github.workspace }}/${{ matrix.freelancer-repository }}
